//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurreyDigitalServices.Locate.Test.SinglePoint {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService", ConfigurationName="SinglePoint.SearchServiceSoap")]
    public interface SearchServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Spat" +
            "ialBoundarySearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData SpatialBoundarySearch(string AdapterName, string Boundary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Spat" +
            "ialBoundarySearch", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SpatialBoundarySearchAsync(string AdapterName, string Boundary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Spat" +
            "ialRadialSearchByEastingNorthing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData SpatialRadialSearchByEastingNorthing(string AdapterName, string Easting, string Northing, string Unit, string Distance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Spat" +
            "ialRadialSearchByEastingNorthing", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SpatialRadialSearchByEastingNorthingAsync(string AdapterName, string Easting, string Northing, string Unit, string Distance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Simp" +
            "leSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData SimpleSearch(string AdapterName, string SearchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Simp" +
            "leSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SimpleSearchAsync(string AdapterName, string SearchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Adva" +
            "ncedSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData AdvancedSearch(string AdapterName, string SearchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Adva" +
            "ncedSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> AdvancedSearchAsync(string AdapterName, string SearchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Adva" +
            "ncedCustomSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData AdvancedCustomSearch(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Adva" +
            "ncedCustomSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> AdvancedCustomSearchAsync(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Sear" +
            "ch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData Search(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Sear" +
            "ch", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SearchAsync(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetA" +
            "dapters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.AdapterCollection GetAdapters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetA" +
            "dapters", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.AdapterCollection> GetAdaptersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Sear" +
            "chFieldsSupported", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported SearchFieldsSupported(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Sear" +
            "chFieldsSupported", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported> SearchFieldsSupportedAsync(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetS" +
            "earchFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetSearchFields(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetS" +
            "earchFields", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetSearchFieldsAsync(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Resu" +
            "ltFieldsSupported", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported ResultFieldsSupported(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/Resu" +
            "ltFieldsSupported", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported> ResultFieldsSupportedAsync(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetR" +
            "esultFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetResultFields(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetR" +
            "esultFields", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetResultFieldsAsync(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetR" +
            "eturnFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetReturnFields(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetR" +
            "eturnFields", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetReturnFieldsAsync(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetA" +
            "llFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
        SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetAllFields(string AdapterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService/GetA" +
            "llFields", ReplyAction="*")]
        System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetAllFieldsAsync(string AdapterName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class SearchResultData : ServiceResult {
        
        private SearchResults resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SearchResults Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class SearchResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchResultItem[] itemsField;
        
        private int pageCountField;
        
        private int fullResultsCountField;
        
        private SearchToken tokenField;
        
        private System.Data.DataSet bluelightDataSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SearchResultItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
                this.RaisePropertyChanged("PageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int FullResultsCount {
            get {
                return this.fullResultsCountField;
            }
            set {
                this.fullResultsCountField = value;
                this.RaisePropertyChanged("FullResultsCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SearchToken Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Data.DataSet BluelightDataSet {
            get {
                return this.bluelightDataSetField;
            }
            set {
                this.bluelightDataSetField = value;
                this.RaisePropertyChanged("BluelightDataSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class SearchResultItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool fullAddressField;
        
        private string managementSystemUrlField;
        
        private int trackerValueField;
        
        private FieldInfo[] fieldItemsField;
        
        private string[] formattedAddressElementsField;
        
        private BNGCoordinates coordinatesField;
        
        private string textToDisplayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool FullAddress {
            get {
                return this.fullAddressField;
            }
            set {
                this.fullAddressField = value;
                this.RaisePropertyChanged("FullAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ManagementSystemUrl {
            get {
                return this.managementSystemUrlField;
            }
            set {
                this.managementSystemUrlField = value;
                this.RaisePropertyChanged("ManagementSystemUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TrackerValue {
            get {
                return this.trackerValueField;
            }
            set {
                this.trackerValueField = value;
                this.RaisePropertyChanged("TrackerValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public FieldInfo[] FieldItems {
            get {
                return this.fieldItemsField;
            }
            set {
                this.fieldItemsField = value;
                this.RaisePropertyChanged("FieldItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public string[] FormattedAddressElements {
            get {
                return this.formattedAddressElementsField;
            }
            set {
                this.formattedAddressElementsField = value;
                this.RaisePropertyChanged("FormattedAddressElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public BNGCoordinates Coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
                this.RaisePropertyChanged("Coordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TextToDisplay {
            get {
                return this.textToDisplayField;
            }
            set {
                this.textToDisplayField = value;
                this.RaisePropertyChanged("TextToDisplay");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class FieldInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldDataType dataTypeField;
        
        private bool isIndexField;
        
        private bool isSearchFieldField;
        
        private bool isReturnFieldField;
        
        private bool isResultListFieldField;
        
        private bool isAddressFieldField;
        
        private string addressClassField;
        
        private string tagField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string expressionField;
        
        private short groupField;
        
        private short sequenceField;
        
        private string valueField;
        
        private bool valueIsBlankField;
        
        private string defaultValueField;
        
        private string dataValuesListField;
        
        private FieldAutoCompleteType autoCompleteTypeField;
        
        private bool valuesAreInWebConfigField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FieldDataType dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsIndex {
            get {
                return this.isIndexField;
            }
            set {
                this.isIndexField = value;
                this.RaisePropertyChanged("IsIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsSearchField {
            get {
                return this.isSearchFieldField;
            }
            set {
                this.isSearchFieldField = value;
                this.RaisePropertyChanged("IsSearchField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsReturnField {
            get {
                return this.isReturnFieldField;
            }
            set {
                this.isReturnFieldField = value;
                this.RaisePropertyChanged("IsReturnField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsResultListField {
            get {
                return this.isResultListFieldField;
            }
            set {
                this.isResultListFieldField = value;
                this.RaisePropertyChanged("IsResultListField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsAddressField {
            get {
                return this.isAddressFieldField;
            }
            set {
                this.isAddressFieldField = value;
                this.RaisePropertyChanged("IsAddressField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AddressClass {
            get {
                return this.addressClassField;
            }
            set {
                this.addressClassField = value;
                this.RaisePropertyChanged("AddressClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
                this.RaisePropertyChanged("Expression");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public short Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public short Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool ValueIsBlank {
            get {
                return this.valueIsBlankField;
            }
            set {
                this.valueIsBlankField = value;
                this.RaisePropertyChanged("ValueIsBlank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
                this.RaisePropertyChanged("DefaultValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DataValuesList {
            get {
                return this.dataValuesListField;
            }
            set {
                this.dataValuesListField = value;
                this.RaisePropertyChanged("DataValuesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public FieldAutoCompleteType AutoCompleteType {
            get {
                return this.autoCompleteTypeField;
            }
            set {
                this.autoCompleteTypeField = value;
                this.RaisePropertyChanged("AutoCompleteType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool ValuesAreInWebConfig {
            get {
                return this.valuesAreInWebConfigField;
            }
            set {
                this.valuesAreInWebConfigField = value;
                this.RaisePropertyChanged("ValuesAreInWebConfig");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public enum FieldDataType {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Bool,
        
        /// <remarks/>
        MultiSelectList,
        
        /// <remarks/>
        AutoCompleteString,
        
        /// <remarks/>
        Label,
        
        /// <remarks/>
        Hidden,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public enum FieldAutoCompleteType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Postcodes,
        
        /// <remarks/>
        Streets,
        
        /// <remarks/>
        Units,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class AdapterInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long keyField;
        
        private string labelField;
        
        private string descriptionField;
        
        private bool nlpgField;
        
        private string tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Nlpg {
            get {
                return this.nlpgField;
            }
            set {
                this.nlpgField = value;
                this.RaisePropertyChanged("Nlpg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class SearchField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tagField;
        
        private FieldInfo fieldField;
        
        private TextSearchOptions optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FieldInfo Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TextSearchOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
                this.RaisePropertyChanged("Options");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class TextSearchOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool matchPartialValuesField;
        
        private bool phoneticSearchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool MatchPartialValues {
            get {
                return this.matchPartialValuesField;
            }
            set {
                this.matchPartialValuesField = value;
                this.RaisePropertyChanged("MatchPartialValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool PhoneticSearch {
            get {
                return this.phoneticSearchField;
            }
            set {
                this.phoneticSearchField = value;
                this.RaisePropertyChanged("PhoneticSearch");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class AnonymousSearchText : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private TextSearchOptions optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TextSearchOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
                this.RaisePropertyChanged("Options");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSearchToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryToken))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public abstract partial class SearchToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isWebServiceSearchField;
        
        private int totalResultsFoundField;
        
        private bool isSpatialSearchField;
        
        private bool pagedResultsField;
        
        private int pageItemCountField;
        
        private int pageIndexField;
        
        private int pageLookAheadCountField;
        
        private string[] orderByFieldTagsField;
        
        private string[] returnFieldTagsField;
        
        private bool returnAllFieldsField;
        
        private int minItemRowNumField;
        
        private int maxItemRowNumField;
        
        private int commandTimeoutField;
        
        private bool isAdddressBaseDataField;
        
        private bool returnQasNameRawAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsWebServiceSearch {
            get {
                return this.isWebServiceSearchField;
            }
            set {
                this.isWebServiceSearchField = value;
                this.RaisePropertyChanged("IsWebServiceSearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalResultsFound {
            get {
                return this.totalResultsFoundField;
            }
            set {
                this.totalResultsFoundField = value;
                this.RaisePropertyChanged("TotalResultsFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsSpatialSearch {
            get {
                return this.isSpatialSearchField;
            }
            set {
                this.isSpatialSearchField = value;
                this.RaisePropertyChanged("IsSpatialSearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool PagedResults {
            get {
                return this.pagedResultsField;
            }
            set {
                this.pagedResultsField = value;
                this.RaisePropertyChanged("PagedResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PageItemCount {
            get {
                return this.pageItemCountField;
            }
            set {
                this.pageItemCountField = value;
                this.RaisePropertyChanged("PageItemCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PageLookAheadCount {
            get {
                return this.pageLookAheadCountField;
            }
            set {
                this.pageLookAheadCountField = value;
                this.RaisePropertyChanged("PageLookAheadCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] OrderByFieldTags {
            get {
                return this.orderByFieldTagsField;
            }
            set {
                this.orderByFieldTagsField = value;
                this.RaisePropertyChanged("OrderByFieldTags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public string[] ReturnFieldTags {
            get {
                return this.returnFieldTagsField;
            }
            set {
                this.returnFieldTagsField = value;
                this.RaisePropertyChanged("ReturnFieldTags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool ReturnAllFields {
            get {
                return this.returnAllFieldsField;
            }
            set {
                this.returnAllFieldsField = value;
                this.RaisePropertyChanged("ReturnAllFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int MinItemRowNum {
            get {
                return this.minItemRowNumField;
            }
            set {
                this.minItemRowNumField = value;
                this.RaisePropertyChanged("MinItemRowNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int MaxItemRowNum {
            get {
                return this.maxItemRowNumField;
            }
            set {
                this.maxItemRowNumField = value;
                this.RaisePropertyChanged("MaxItemRowNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CommandTimeout {
            get {
                return this.commandTimeoutField;
            }
            set {
                this.commandTimeoutField = value;
                this.RaisePropertyChanged("CommandTimeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsAdddressBaseData {
            get {
                return this.isAdddressBaseDataField;
            }
            set {
                this.isAdddressBaseDataField = value;
                this.RaisePropertyChanged("IsAdddressBaseData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool ReturnQasNameRawAddress {
            get {
                return this.returnQasNameRawAddressField;
            }
            set {
                this.returnQasNameRawAddressField = value;
                this.RaisePropertyChanged("ReturnQasNameRawAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryToken))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public abstract partial class TextSearchToken : SearchToken {
        
        private SearchMode searchModeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SearchMode SearchMode {
            get {
                return this.searchModeField;
            }
            set {
                this.searchModeField = value;
                this.RaisePropertyChanged("SearchMode");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public enum SearchMode {
        
        /// <remarks/>
        DrillDown,
        
        /// <remarks/>
        AllFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class QueryToken : TextSearchToken {
        
        private AnonymousSearchText searchTextField;
        
        private SearchField[] qualifiedValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AnonymousSearchText SearchText {
            get {
                return this.searchTextField;
            }
            set {
                this.searchTextField = value;
                this.RaisePropertyChanged("SearchText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SearchField[] QualifiedValues {
            get {
                return this.qualifiedValuesField;
            }
            set {
                this.qualifiedValuesField = value;
                this.RaisePropertyChanged("QualifiedValues");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class BNGCoordinates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double eastingField;
        
        private double northingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Easting {
            get {
                return this.eastingField;
            }
            set {
                this.eastingField = value;
                this.RaisePropertyChanged("Easting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Northing {
            get {
                return this.northingField;
            }
            set {
                this.northingField = value;
                this.RaisePropertyChanged("Northing");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class ServiceError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorTypeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
                this.RaisePropertyChanged("ErrorType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldInfoCollection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FeatureSupported))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdapterCollection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchResultData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class ServiceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class FieldInfoCollection : ServiceResult {
        
        private FieldInfo[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public FieldInfo[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class FeatureSupported : ServiceResult {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aligned-assets.co.uk/SinglePoint/Search/WebServices/SearchService")]
    public partial class AdapterCollection : ServiceResult {
        
        private AdapterInfo[] adaptersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public AdapterInfo[] Adapters {
            get {
                return this.adaptersField;
            }
            set {
                this.adaptersField = value;
                this.RaisePropertyChanged("Adapters");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchServiceSoapChannel : SurreyDigitalServices.Locate.Test.SinglePoint.SearchServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceSoapClient : System.ServiceModel.ClientBase<SurreyDigitalServices.Locate.Test.SinglePoint.SearchServiceSoap>, SurreyDigitalServices.Locate.Test.SinglePoint.SearchServiceSoap {
        
        public SearchServiceSoapClient() {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData SpatialBoundarySearch(string AdapterName, string Boundary) {
            return base.Channel.SpatialBoundarySearch(AdapterName, Boundary);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SpatialBoundarySearchAsync(string AdapterName, string Boundary) {
            return base.Channel.SpatialBoundarySearchAsync(AdapterName, Boundary);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData SpatialRadialSearchByEastingNorthing(string AdapterName, string Easting, string Northing, string Unit, string Distance) {
            return base.Channel.SpatialRadialSearchByEastingNorthing(AdapterName, Easting, Northing, Unit, Distance);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SpatialRadialSearchByEastingNorthingAsync(string AdapterName, string Easting, string Northing, string Unit, string Distance) {
            return base.Channel.SpatialRadialSearchByEastingNorthingAsync(AdapterName, Easting, Northing, Unit, Distance);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData SimpleSearch(string AdapterName, string SearchText) {
            return base.Channel.SimpleSearch(AdapterName, SearchText);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SimpleSearchAsync(string AdapterName, string SearchText) {
            return base.Channel.SimpleSearchAsync(AdapterName, SearchText);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData AdvancedSearch(string AdapterName, string SearchText) {
            return base.Channel.AdvancedSearch(AdapterName, SearchText);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> AdvancedSearchAsync(string AdapterName, string SearchText) {
            return base.Channel.AdvancedSearchAsync(AdapterName, SearchText);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData AdvancedCustomSearch(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token) {
            return base.Channel.AdvancedCustomSearch(AdapterName, token);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> AdvancedCustomSearchAsync(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token) {
            return base.Channel.AdvancedCustomSearchAsync(AdapterName, token);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData Search(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token) {
            return base.Channel.Search(AdapterName, token);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.SearchResultData> SearchAsync(string AdapterName, SurreyDigitalServices.Locate.Test.SinglePoint.QueryToken token) {
            return base.Channel.SearchAsync(AdapterName, token);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.AdapterCollection GetAdapters() {
            return base.Channel.GetAdapters();
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.AdapterCollection> GetAdaptersAsync() {
            return base.Channel.GetAdaptersAsync();
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported SearchFieldsSupported(string AdapterName) {
            return base.Channel.SearchFieldsSupported(AdapterName);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported> SearchFieldsSupportedAsync(string AdapterName) {
            return base.Channel.SearchFieldsSupportedAsync(AdapterName);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetSearchFields(string AdapterName) {
            return base.Channel.GetSearchFields(AdapterName);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetSearchFieldsAsync(string AdapterName) {
            return base.Channel.GetSearchFieldsAsync(AdapterName);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported ResultFieldsSupported(string AdapterName) {
            return base.Channel.ResultFieldsSupported(AdapterName);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FeatureSupported> ResultFieldsSupportedAsync(string AdapterName) {
            return base.Channel.ResultFieldsSupportedAsync(AdapterName);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetResultFields(string AdapterName) {
            return base.Channel.GetResultFields(AdapterName);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetResultFieldsAsync(string AdapterName) {
            return base.Channel.GetResultFieldsAsync(AdapterName);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetReturnFields(string AdapterName) {
            return base.Channel.GetReturnFields(AdapterName);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetReturnFieldsAsync(string AdapterName) {
            return base.Channel.GetReturnFieldsAsync(AdapterName);
        }
        
        public SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection GetAllFields(string AdapterName) {
            return base.Channel.GetAllFields(AdapterName);
        }
        
        public System.Threading.Tasks.Task<SurreyDigitalServices.Locate.Test.SinglePoint.FieldInfoCollection> GetAllFieldsAsync(string AdapterName) {
            return base.Channel.GetAllFieldsAsync(AdapterName);
        }
    }
}
